### ISSUE TITLE
Handling binary Hi-C tracks

### ISSUE THREAD

**Issue by srcoulombe** [tanaylab/misha#1]
Hi! I'm trying to analyze an individual replicate from the Hi-C files published in Bonev et al. 2017 ([GEO link](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96107) ). I'd specifically like to get the Hi-C matrix (at 50Kb resolution) for the chromosome 1 - chromosome 1 track from [this replicate](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2533818). 

What I've done so far is:
1. download the gunzipped tarball from [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2533818)
2. unzipped the tarball into the ```gc_cn1.track``` directory (with files like ```chr1-chr1```, ```chr1-chr2```, etc...)
3. created a misha database for mm10 by following [these instructions](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2533818)
4. moved the ```gc_cn1.track``` directory  to the ./tracks subdir of my misha database

I'm able to see the ```gc_cn1``` track when using ```gtrack.ls()```, but I'm stumped on how I could get and save the 50Kb intra-chromosomal Hi-C matrices to a .csv file from here on out (either as dense matrices or in a tabular format). I didn't see anything in the [manual](https://tanaylab.github.io/misha/articles/manual.pdf) on that topic, would any of you have any suggestions?

Cheers!

**Comment by aviezerl** [comment]
In order to create a hic matrix with 50kb resolution, you need to:

Create a virtual track with function `area`:
```r
gvtrack.create("gc_cn_50k", "gc_cn1", func="area")
```
Create a grid iterator with resolution of 50k:
```r
iter1d <- giterator.intervals(intervals = gintervals(1), iterator=5e4)
iter <- giterator.cartesian_grid(iter1d, iter1d, expansion1=c(-2.5e4, 2.5e4))
```

Extract the virtual track and save the result:
```r
gextract("gc_cn_50k", gintervals.2d.all(), iterator=iter, file="gc_cn_50k.tsv")
```

Note that if you are interested only in a single chromosome you can reduce computation by setting the intervals set to:

``` r
intervals <- gintervals.2d(chroms1 = "chr1", chroms2 = "chr1")
gextract("gc_cn_50k", intervals=intervals, iterator=iter, file ="gc_cn_50k.tsv" )
```

Aviezer

**Comment by srcoulombe** [comment]
Thanks for the super quick reply! I've tried to follow your instructions, but the step where the virtual track is created raises the error ```Error: Invalid format of track at <path/to/track>```.

My best guess is that misha expects the track to be a tabular text file but the tracks are binary files? I'm basing that guess on [this comment from N. Mendelson](https://bitbucket.org/tanaylab/shaman/issues/17/is-there-a-way-to-use-shaman-to-read-the#comment-53963577), but I'm still working on how to work around that error. 

If you have any advice, I'd love to hear from you again!

**Comment by srcoulombe** [comment]
Hi, I've tried a few different tests since the last comment but I'm still unable to read any of those binary files from GEO. If anyone has any clue on how to load those tracks, I'd really appreciate if they could share tips!

**Comment by GDemon486** [comment]
I also have the same question. Could the author please provide at least an explanation of how these binary files are generated? I attempted to decode them using the _unserialize_ function in R, but it couldn't recognize these files. I also noticed the presence of the _RSaneUnserialize_ function in the C++ part of the source code. However, since I am not proficient in C++, I am unable to make effective function calls. I hope to write a script to interpret these files and would appreciate the author's assistance based on some instructions. Thank you very much!

cheers！

**Comment by aviezerl** [comment]
The binary files are generated using the c++ code at the `misha` package and are saved in a non-trivial quadtree format. The best way to unserialize them is by using the package itself. I tried to download the files mentioned at the beginning of the issue + run the above commands and did not have any error - could you please send me the exact commands you are running + the error message?

**Comment by GDemon486** [comment]
Dear Aviezer Lifshitz


Here is my process and results.


Step1: I first established the reference library for mm10.
ftp <-"ftp://hgdownload.soe.ucsc.edu/goldenPath/mm10"


gdb.create("mm10",
           paste(ftp, 'chromosomes',paste0('chr', c(1:19, 'X','Y','M'),'.fa.gz'),sep='/'),
           paste(ftp, "database/knownGene.txt.gz",sep="/"),
           paste(ftp, "database/kgXref.txt.gz",sep="/"),
           c("kgID", "mRNA","spID","spDisplayID","geneSymbol",
             "refseq", "protAcc","description","rfamAcc",
             "tRnaName"))
gdb.init('mm10')




Step2:Unpack the GSM2533821_gc_es4.tar.gz file, and move the extracted gc_es4.track folder to the ./mm10/tracks/ directory.
tar -xzvfGSM2533821_gc_es4.tar.gz
mv gc_es4.track./mm10/tracks


Step3: try to create gvtrack
> gvtrack.create("gc_es4_50k", "gc_es4",func="area")
Error: Sourceofvirtualtrackgc_es4_50kwasnotrecognizedneitherasatracknorasintervals
> gvtrack.create("gc_es4_50k", "gc_es4.track",func="area")
Error: Sourceofvirtualtrackgc_es4_50kwasnotrecognizedneitherasatracknorasintervals
> gvtrack.create("gc_es4_50k", "./mm10/tracks/gc_es4.track",func="area")
Error: Sourceofvirtualtrackgc_es4_50kwasnotrecognizedneitherasatracknorasintervals
> gvtrack.create("gc_es4_50k", "./mm10/tracks/gc_es4",func="area")
Error: Sourceofvirtualtrackgc_es4_50kwasnotrecognizedneitherasatracknorasintervals




In the first two steps, I encountered no errors; however, during the third step, I was unable to successfully create the gvtrack.
Do you have any suggestions regarding this outcome? Thank you very much for your assistance, and I look forward to your reply.


Best Regards,
Zhanyu Gao
---- Replied Message ----
| From | Aviezer ***@***.***> |
| Date | 1/4/2024 22:07 |
| To | ***@***.***> |
| Cc | Gaozhan ***@***.***> ,
***@***.***> |
| Subject | Re: [tanaylab/misha] Handling binary Hi-C tracks (#1) |

The binary files are generated using the c++ code at the misha package and are saved in a non-trivial quadtree format. The best way to unserialize them is by using the package itself. I tried to download the files mentioned at the beginning of the issue + run the above commands and did not have any error - could you please send me the exact commands you are running + the error message?

**Comment by aviezerl** [comment]
I think what is missing between step 2 and 3 is a call to: 

```r
gsetroot('mm10')
gdb.reload()
```

`gdb.reload` rebuilds the track index of the misha database and this is needed due to the addition of the track externally. 

Can you try adding this step?

**Comment by GDemon486** [comment]
Thank you very much for your assistance. With these commands, I have successfully generated the TSV file.


---- Replied Message ----






I think what is missing between step 2 and 3 is a call to:

gsetroot('mm10')
gdb.reload()

gdb.reload rebuilds the track index of the misha database and this is needed due to the addition of the track externally.

Can you try adding this step?

**Comment by aviezerl** [comment]
Great
