### ISSUE TITLE
4.0.11's HashFunc.h change breaks non-GCC builds

### ISSUE THREAD

**Issue by jmarshall** [tanaylab/misha#3]
I'm afraid the recent change to _src/HashFunc.h_ in 7df1c7def9935c3439fb0fa0236c0bec3e15ba17 doesn't compile on macOS with Clang, due to:

```diff
-	template<> struct hash< std::pair<size_t, size_t> >
+ 	template<> struct hash< std::pair<uint64_t, uint64_t> >
```

I guess with GCC `size_t` is similarly defined to `uint64_t` so this new instantiation is close enough. However with Clang building fails (with dozens of obscure error messages) because what it needs is an instantiation of `template<> struct hash< std::pair<size_t, size_t> >` and that's now missing.

This could be fixed by adding another instantiation, e.g.,

```diff
+       template<> struct hash< std::pair<size_t, size_t> >
+       {
+               size_t operator()(const std::pair<size_t, size_t> &v) const {
+                       std::pair<uint64_t, uint64_t> v64(v.first, v.second);
+                       return std::hash<std::pair<uint64_t, uint64_t> >()(v64);
+               }
+       };
```

Or by changing the main one back to `size_t, size_t` and casting `first` and `second` to `uint64_t` on the inside of the function perhaps.

(Sorry to be the bearer of bad news again! See the build log at bioconda/bioconda-recipes#25396.)

**Comment by hoichman** [comment]
Yep, we noticed it already. :) The trouble is that size_t is defined differently on various systems.

Working on the fix...

**Comment by hoichman** [comment]
Fixed.
