### ISSUE TITLE
`gtrack.2d.import()`  Cannot create track.

### ISSUE THREAD

**Issue by jiangpuxuan** [tanaylab/misha#6]
Here is my code:
```
gtrack.2d.import(
  track=my_track_name, 
  description="observed hic data", 
  file=c(my_shaman_data))

gdb.reload()
```
The error is :
```
Error: Cannot create track at /usr/local/lib/R/site-library/misha/trackdb/test/tracks/grnsmile_hic_obs.track: Permission denied
```

I am not a sudo user , so I cannot create a certain file in the path ` /usr/local/lib/R/site-library/misha/trackdb/test/tracks/`.....
So is it necessary to have sudo authority in `gtrack.2d.import()` ?

Thank you for your help!

**Comment by aviezerl** [comment]
Hi @jiangpuxuan, 

I think you are trying to create a track in the examples database, in which you do not have sufficient permissions. I suggest you first create a misha database for the desired genome, see examples here: 

https://tanaylab.github.io/shaman/articles/import.html#create-misha-database-from-ucsc

then, set the root to your newly created database with `gsetroot` and create your 2D track.

**Comment by jiangpuxuan** [comment]
> Hi @jiangpuxuan,
> 
> I think you are trying to create a track in the examples database, in which you do not have sufficient permissions. I suggest you first create a misha database for the desired genome, see examples here:
> 
> https://tanaylab.github.io/shaman/articles/import.html#create-misha-database-from-ucsc
> 
> then, set the root to your newly created database with `gsetroot` and create your 2D track.

Oh, I solved it by change the path.
